package Types

/*
NOTE(A-Boring-Square):
This is Engine internal embeded data like the splash screen DO NOT edit this file
*/

@(rodata)
SplashImage := #load("../Icons/MagmaEngine.png", []byte)

@(rodata)
EngineVersion := [?]int{1, 0, 0}