
[Developers]
"Lead Developer" = "Lilly Yurchenko"
"Assistant Developer" = "Everet Bradford"

[Assets]


[Sound]
"Mostly Moosey" = "moosey_scream.mp3"

[Testers]


["Special Thanks"]
"Players" = "For playing our game"